### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by red031000** [TwitchPlaysPokemon/public#126]
gonna create a todo list of things that I'd normally fix as I notice them during everything going on, so devs can fix them

- [x] fix spanish switching regex
- [ ] align hashtags with music information in the overlay
- [x] fix felk command
- [x] increase likelihood of languages appearing from 0.1 to 0.125
- [ ] add p as an alias to wait in sidegame
